# Generated by Django 6.1.1 on 2026-09-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='የተኑ ስም (ለምሳሌ: Play Bingo 🎮)', max_length=100)),
                ('url', models.URLField(blank=True, help_text='የዌብ አፕ ወይም የድር ጣቢያ ሊንክ', null=True)),
                ('is_web_app', models.BooleanField(default=False, help_text='ይህ በተን Mini App (WebApp) የሚከፍት ከሆነ ቲክ ያድርጉት')),
                ('order', models.IntegerField(default=0, help_text='የተኖች ቅደም ተከተል ቁጥር (ለምሳሌ: 1, 2, 3...)')),
                ('is_active', models.BooleanField(default=True, help_text='ቦቱ ላይ እንዲታይ ከፈለጉ ቲክ ያድርጉ')),
            ],
        ),
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.TextField(default='Welcome to Edil Bingo! Choose an option below.')),
                ('logo', models.ImageField(blank=True, help_text='የቦቱን ሎጎ ፎቶ እዚህ ይጫኑ', null=True, upload_to='bot_logos/')),
            ],
        ),
    ]
